---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for xyla
    tags: always
    authorized_key:
      user: xyla
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDc4xP/mdHqfeO8khMXvG+3adsgCmsBd9vYlHxIPeRHlNOf0x6XipCJBftHz0NJ8YgGRGubTvTLCXLNNtOHQ8oWuIoOlZU148Enatqgq+PrOxfe0w2i2ljqHgrdCnOqDXyL9gaRbKpNzxFDyHIDtujbiwXNEEy/eETYO55Tu97qTodGYSVlCjWxWQaL0s4yUBF+NwiW9n+zJoMdfSwi+0vZqqn5qmNSfICVDKGeZ6IBGI/6BTjNz2vUU3ZaSfYNIADMn4g/d3Lgz8co6rSxK2NAkwGSOX+5xJ4EbP1F66hDFFp92b1gGiCj3dUtZpTWzB9xKIF1LFaFsBc4p/58pSzcX9r3kl8ZjaAWB1lpGmEq3fFTKg//3Vu7yxTQgNAFaGYl1jepOIPLjohSOCkZN0WXgU9Ysi176m6avjC4d3M5ZZX/LTtNHirSJnJId/+Tt5zU6Ezm8dH1kBPzuTmeMbIDPWYr15EnUaGapJbun8UuTNJfRZwnKVVJl7lWL8/HK50= root@ansible-xy"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache2
    service:
      name: apache2
      state: started

  - name: change e-mail address for admin
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: restart apache2
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

